export default {
  movie: require('./categories/movie.png'),
  sport: require('./categories/sport.png'),
  party: require('./categories/party.png'),
  concert: require('./categories/concert.png'),
  culture: require('./categories/culture.png'),
  education: require('./categories/education.png'),
  food: require('./categories/food.png'),
  gaming: require('./categories/gaming.png'),
  health: require('./categories/health.png'),
  language: require('./categories/language.png'),
  music: require('./categories/music.png'),
  photo: require('./categories/photo.png'),
  shoping: require('./categories/shoping.png'),
  travel: require('./categories/travel.png'),

  homeActive: require('./navbar/home-active.png'),
  homeInactive: require('./navbar/home-inactive.png'),
  codeActive: require('./navbar/code-active.png'),
  codeInactive: require('./navbar/code-inactive.png'),
  createEventActive: require('./navbar/add-active.png'),
  createEventInactive: require('./navbar/add-inactive.png'),
  chatActive: require('./navbar/chat-active.png'),
  chatInactive: require('./navbar/chat-inactive.png'),
  profileActive: require('./navbar/profile-active.png'),
  profileInactive: require('./navbar/profile-inactive.png'),

  addButton: require('./add-button.png'),
  search: require('./search.png'),
  filter: require('./filter.png'),
  option: require('./option.png'),
  editProfile: require('./edit-profile.png'),
  logout: require('./logout.png'),
  changeImage: require('./change-image.png'),
  back: require('./back.png'),
  interest: require('./interest.png'),

  img: require('./img.png'),
  location: require('./location.png'),
  peoples: require('./peoples.png'),
  time: require('./time.png'),
  calendar: require('./calendar.png'),
  tick: require('./tick.png'),
  cross: require('./cross.png'),
  profile: require('./profile.png'),
};
