export default {
  movie: require('./categories/movie.png'),
  sport: require('./categories/sport.png'),
  party: require('./categories/party.png'),

  homeActive: require('./navbar/home-active.png'),
  homeInactive: require('./navbar/home-inactive.png'),
  qrActive: require('./navbar/qr-inactive.png'),
  qrInactive: require('./navbar/qr-inactive.png'),
  createEventActive: require('./navbar/add-active.png'),
  createEventInactive: require('./navbar/add-inactive.png'),
  chatActive: require('./navbar/chat-active.png'),
  chatInactive: require('./navbar/chat-inactive.png'),
  profileActive: require('./navbar/profile-active.png'),
  profileInactive: require('./navbar/profile-inactive.png'),

  addButton: require('./add-button.png'),
  search: require('./search.png'),
  filter: require('./filter.png'),
  option: require('./option.png'),
  editProfile: require('./edit-profile.png'),
  logout: require('./logout.png'),
  changeImage: require('./change-image.png'),

  img: require('./img.png'),
  location: require('./location.png'),
  peoples: require('./peoples.png'),
  time: require('./time.png'),
  calendar: require('./calendar.png'),
  tick: require('./tick.png'),
  cross: require('./cross.png'),
};
