export default {
  onboard1: require('./onboard1.png'),
  onboard2: require('./onboard2.png'),
  onboard3: require('./onboard3.png'),
  blankNewTask: require('./blankNewTask.png'),
  blankTask: require('./blankTask.png'),
  idcard: require('./idcard.png'),
  pirotcer: require('./pirotcer.png'),
  dronecer: require('./dronecer.png'),
  marker: require('./marker.png'),
  map: require('./map.png'),
  loading: require('./loading.json'),
  reviewSuccess: require('./reviewSuccess.png'),
  successimage: require('./success.png'),
  successdrone: require('./successdrone.png'),
  blankIncome: require('./blankIncome.png'),
  profile: require('./profile.png'),
  profileActive: require('./profileActive.png'),
  deletePic: require('./deletePic.png'),
  newjobnoti: require('./newjobnoti.png'),
  registerconfirmnoti: require('./registerconfirmnoti.png'),
  registerfailednoti: require('./registerfailednoti.png'),
  troublejobnoti: require('./troublejobnoti.png'),
  troublemissnoti: require('./troublemissnoti.png'),
  emptyhistory : require('./emptyhistory.png')
};
